# Generated by Django 4.0.4 on 2022-05-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('num', models.IntegerField()),
            ],
        ),
    ]
